import StrictLean.Checker.RuleExampleCorpusProjection

#check StrictLean.Checker.JsonProjectionTree.map_insert
#check StrictLean.Checker.JsonProjectionTree.get_map
#check StrictLean.Checker.RuleExampleProjection.qualify_congr
#check StrictLean.Checker.RuleExampleProjection.qualify_record
#check StrictLean.Checker.RuleExampleProjection.qualifyMutations_record
#check StrictLean.Checker.RuleExampleProjection.qualify_record_checkerSources
#check StrictLean.Checker.RuleExampleProjection.qualifyMutations_record_checkerSources
#check StrictLean.Checker.RuleExampleProjection.withoutSourceAccount_view
#check StrictLean.Checker.RuleExampleProjection.qualify_withoutSourceAccount
#check StrictLean.Checker.RuleExampleProjection.qualifyCorpus_records
#check StrictLean.Checker.RuleExampleProjection.qualifyCorpus_congr

#print axioms StrictLean.Checker.JsonProjectionTree.map_insert
#print axioms StrictLean.Checker.JsonProjectionTree.get_map
#print axioms StrictLean.Checker.RuleExampleProjection.qualify_congr
#print axioms StrictLean.Checker.RuleExampleProjection.qualify_record
#print axioms StrictLean.Checker.RuleExampleProjection.qualifyMutations_record
#print axioms StrictLean.Checker.RuleExampleProjection.qualify_record_checkerSources
#print axioms StrictLean.Checker.RuleExampleProjection.qualifyMutations_record_checkerSources
#print axioms StrictLean.Checker.RuleExampleProjection.withoutSourceAccount_view
#print axioms StrictLean.Checker.RuleExampleProjection.qualify_withoutSourceAccount
#print axioms StrictLean.Checker.RuleExampleProjection.qualifyCorpus_records
#print axioms StrictLean.Checker.RuleExampleProjection.qualifyCorpus_congr
