import StrictLeanPolicy.Acceptance

-- Signature/axiom observation only; this file is not a surrogate implementation proof.
#check StrictLeanPolicy.ResultState.collect
#check StrictLeanPolicy.ResultState.collect_success_iff
#check StrictLeanPolicy.ResultState.collect_lookup
#check StrictLeanPolicy.ResultState.collect_empty_lookup
#check StrictLeanPolicy.finalize
#check StrictLeanPolicy.finalize_iff
#check StrictLeanPolicy.finalized_covers_input
#check StrictLeanPolicy.AcceptedRun
#check StrictLeanPolicy.acceptedRun_claim
#check StrictLeanPolicy.combineAccepted
#check StrictLeanPolicy.combined_policy
#check StrictLeanPolicy.combined_reports_same_snapshot
#check StrictLeanPolicy.infrastructure_disjoint
#check StrictLeanPolicy.fileSourceBinding_bytes
#print axioms StrictLeanPolicy.ResultState.collect_success_iff
#print axioms StrictLeanPolicy.ResultState.collect_lookup
#print axioms StrictLeanPolicy.ResultState.collect_empty_lookup
#print axioms StrictLeanPolicy.finalize_iff
#print axioms StrictLeanPolicy.finalized_covers_input
#print axioms StrictLeanPolicy.acceptedRun_claim
#print axioms StrictLeanPolicy.combined_policy
#print axioms StrictLeanPolicy.combined_reports_same_snapshot
#print axioms StrictLeanPolicy.infrastructure_disjoint
#print axioms StrictLeanPolicy.fileSourceBinding_bytes

-- Current environment-indexed and split-execution guarantees, with all hypotheses.
#check StrictLeanPolicy.census_exact_requests
#check StrictLeanPolicy.census_project_partition
#check StrictLeanPolicy.requiredJobs_environment_coverage
#check StrictLeanPolicy.accepted_environment_resolves
#check StrictLeanPolicy.finalize_collection_error
#check StrictLeanPolicy.finalize_of_collected
#check StrictLeanPolicy.finalize_reindexed
#check StrictLeanPolicy.finalize_singleton_transfer
#print axioms StrictLeanPolicy.census_exact_requests
#print axioms StrictLeanPolicy.census_project_partition
#print axioms StrictLeanPolicy.requiredJobs_environment_coverage
#print axioms StrictLeanPolicy.accepted_environment_resolves
#print axioms StrictLeanPolicy.finalize_collection_error
#print axioms StrictLeanPolicy.finalize_of_collected
#print axioms StrictLeanPolicy.finalize_reindexed
#print axioms StrictLeanPolicy.finalize_singleton_transfer
